[project]
name = "blackjack-engine"
version = "0.1.0"
authors = [ { name = "lysapala93" } ]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
dependencies = [
    "numpy>=2.3.5",
    "pytest>=9.0.1",
]
